---
- name: Create POWA database.
  postgresql_db:
    name: powa

- name: Create extensions.
  postgresql_ext:
    name: "{{ item }}"
    db: powa 
  become_user: postgres
  with_items:
    - pg_stat_statements
    - btree_gist
    - powa
    - pg_qualstats
    - pg_stat_kcache
    # extension mast be installed for all dbx in cluster! how to???
    #- hypopg

- name: Get databases list
  command: psql -t -c "select datname from pg_database where datname <> 'template0';"
  become: true
  become_user: postgres
  register: database_list

- name: Create extension powa in databases.
  postgresql_ext:
    name: hypopg 
    db: "{{ item[0] }}"
  become_user: postgres
  with_nested: "{{ database_list.stdout_lines }}"

- name: Create POWA user.
  postgresql_user:
    name: powa
    #password: 
    role_attr_flags: SUPERUSER
