--- 
# seems not working...
- name: Configure firewall. Ingnore if service is not running. 
  firewalld:
    service: postgresql
    permanent: true
    state: enabled
    immediate: true
  ignore_errors: yes

- name: Find if pg cluster already exists.
  find: paths="{{ pg_data }}" file_type=file patterns="PG_VERSION"
  register: pg_dir

- name: Initialize database. Skip this if already exists.
  command: /usr/pgsql-{{ postgresql_version }}/bin/initdb -D {{ pg_data }}
  become: yes
  become_user: "{{ postgresql_admin_user }}"
  when: pg_dir.matched|int == 0

- name: Start and enable postgresql service.
  service: 
    name: "postgresql-{{ postgresql_version }}" 
    state: started 
    enabled: yes
