---
- import_tasks: repository.yml
  tags: 1_repository

- import_tasks: install.yml
  tags: 2_install

- import_tasks: initialize.yml
  tags: 3_init

- import_tasks: postgresql_conf.yml
  tags: 4_config

- import_tasks: extensions.yml
  tags: 5_extensions

- import_tasks: pgbouncer.yml
  tags: 6_pgbouncer

- import_tasks: pgbadger.yml
  tags: 7_pgbadger

- import_tasks: tools.yml
  tags: 8_tools

- import_tasks: mamonsu.yml
  tags: 9_mamonsu
