---
- import_tasks: repository.yml
  tags: 1_repository

- import_tasks: install.yml
  tags: 2_install

- import_tasks: initialize.yml
  tags: 3_init

- import_tasks: postgresql_conf.yml
  tags: 4_config

- import_tasks: pgbadger.yml
  tags: 5_pgbadger
