---
- name: "Install pgBackRest package."
  yum: 
    state: latest
    pkg: "{{ item }}"
  with_items:
    - "pgbackrest"

# backup path default /var/lib/pgsql/xx/backup

- name: Place config for pgBackRest.
  template:
    src: pgbackrest.conf.j2
    dest: /etc/pgbackrest.conf

- name: Create stanza.
  command: pgbackrest --stanza="{{ pgbackrest_stanza }}" --log-level-console=info stanza-create
  become: yes
  become_user: "{{ postgresql_admin_user }}"

- name: Configure cron for pgBackRest full.
  cron:
    name: "pgbackrest full"
    user: "{{ postgresql_admin_user }}"
    minute: "00"
    hour: "03"
    weekday: 0
    job: "pgbackrest --type=full --stanza={{ pgbackrest_stanza }} backup &>/tmp/backup0.log"

- name: Configure cron for pgBackRest diff.
  cron:
    name: "pgbackrest diff"
    user: "{{ postgresql_admin_user }}"
    minute: "00"
    hour: "03"
    weekday: 1-6
    job: "pgbackrest --type=diff --stanza={{ pgbackrest_stanza }} backup &>/tmp/backup1.log"
