---

- name: Install pgbouncer
  yum:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - pgbouncer

- name: Set include additional file in pgbouncer.ini.
  lineinfile: 
      line: "%include /etc/pgbouncer/pgbouncer-ansible.ini"
      dest: "/etc/pgbouncer/pgbouncer.ini"
      backup: yes
  notify: reload pgbouncer

- name: Insert reminder to pgbouncer.ini.
  blockinfile  :
    dest: "/etc/pgbouncer/pgbouncer.ini"
    insertbefore: BOF
    marker: ;######################################################################################
    block: |
      ;
      ; pbouncer configuration is manager by ansible
      ; included /etc/pgbouncer/pgbouncer-ansible.ini takes presidence over this file!
      ;

- name: Copy pgbouncer.ini template. 
  template: owner=root group=root mode=644 
            src=pgbouncer.ini.j2
            dest=/etc/pgbouncer/pgbouncer-ansible.ini
  notify:
    - reload pgbouncer

- name: Add firewall exception. If firewall is on.
  firewalld: port={{ pgbouncer_port }}/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes

- name: Start pgbouncer
  service: 
    name: pgbouncer 
    state: started
    enabled: yes 

