--- 
- name: Create conf.d
  file: path={{ pg_conf }}/conf.d state=directory owner=postgres group=postgres

- name: Create directory for archivelogs. 
  file:
    path: "{{ archivelog_dir }}"
    state: directory
    owner: "{{ postgresql_admin_user }}"
    group: "{{ postgresql_admin_user }}"
    mode: 0755
  when: archivelog_dir is defined
  # error if symlinked to nfs 
  ignore_errors: yes

- name: Set conf.d include in postgresql.conf
  lineinfile: 
      regexp: "^#?include_dir" 
      line: "include_dir = 'conf.d'"
      dest: "{{ pg_conf }}/postgresql.conf"
      backup: yes
  notify: restart postgres

- name: Set config options.
  template: 
      src: 25ansible_postgresql.conf.j2
      dest: "{{ pg_conf }}/conf.d/25ansible_postgresql.conf"
      owner: "{{ postgresql_admin_user }}"
      group: "{{ postgresql_admin_user }}"
      backup: yes
  notify: restart postgres

- name: Start and enable postgresql service.
  service: 
    name: "postgresql-{{ postgresql_version }}" 
    state: started 
    enabled: yes
  when: postgresql_

- meta: flush_handlers

